models/todo.py
import time

from models import Model
from utils import formatted_time, log


class Todo(Model):
    """
    针对我们的数据 TODO
    我们要做 4 件事情
    C create 创建数据
    R read 读取数据
    U update 更新数据
    D delete 删除数据

    Todo.new() 来创建一个 todo
    """

    @classmethod
    def valid_names(cls):
        names = super().valid_names()
        names = names + [
            'task',
            'created_time',
            'updated_time',
        ]
        return names

    @classmethod
    def new(cls, form):
        m = super().new(form)
        t = int(time.time())
        m.created_time = t
        m.updated_time = t
        m.save()
        return m

    @classmethod
    def update(cls, id, form):
        m = super().update(id, form)
        log('todo update', m)
        m.updated_time = int(time.time())
        m.save()
        return m

    def formatted_created_time(self):
        return formatted_time(self.created_time)

    def formatted_updated_time(self):
        return formatted_time(self.updated_time)

routes/api_blog.py
from flask import (
    jsonify,
    Blueprint,
    request,
    redirect,
    url_for,
    session,
)

from utils import log
from models.blog import Blog
from routes import current_user
main = Blueprint('blog_api', __name__)


# 本文件只返回 json 格式的数据
# 而不是 html 格式的数据


@main.route('/all', methods=['GET'])
def all():
    blogs = Blog.all_json()
    return jsonify(blogs)


@main.route('/detail', methods=['GET'])
def detail():
    blog_id = int(request.args.get('id'))
    b = Blog.find(blog_id)
    return jsonify(b.json())


@main.route('/add', methods=['POST'])
def add():
    # 得到浏览器发送的表单, 浏览器用 ajax 发送 json 格式的数据过来
    # 所以这里我们用新增加的 json 函数来获取格式化后的 json 数据
    form = request.form
    u = current_user()
    # 创建一个 blog
    Blog.new(form, u.username)
    # 把创建好的 blog 返回给浏览器
    return redirect(url_for('blog.index'))


@main.route('/delete', methods=['GET'])
def delete():
    blog_id = int(request.args.get('id'))
    t = Blog.delete(blog_id)
    return jsonify(t.json())


@main.route('/update', methods=['POST'])
def update():
    form = request.get_json()
    blog_id = int(form.get('id'))
    t = Blog.update(blog_id, form)
    return jsonify(t.json())

routes/api_user.py
from flask import (
    redirect,
    Blueprint,
    request,
    session,
    url_for,
)

from utils import log
from models.user import User

main = Blueprint('user_api', __name__)


@main.route('/login', methods=['POST'])
def login():
    """
    登录页面的路由函数
    """
    log('login, cookies', request.cookies)
    form = request.form
    u = User.new(form)
    if u.validate_login():
        u = User.find_by(username=u.username)
        session['user_id'] = u.id
        log('session', session)
        # 登录后定向到 /
        return redirect(url_for('static.index'))
    else:
        return redirect(url_for('user.login'))


@main.route('/register', methods=['POST'])
def register():
    """
    注册页面的路由函数
    """
    form = request.form
    u = User.new(form)
    if u.validate_register():
        # 注册成功再保存
        u.save()
        # 注册成功后 定向到登录页面
        return redirect(url_for('user.login'))
    else:
        # 注册失败 定向到注册页面
        return redirect(url_for('user.register'))

routes/routes_blog.py
from flask import (
    render_template,
    Blueprint,
)

# 创建一个蓝图对象
# 路由都定义在蓝图对象中
# 然后再 flask 主代码中 注册蓝图 来使用
# 第一个参数是蓝图的名字 以后会有用
# 第二个参数是套路
main = Blueprint('blog', __name__)


@main.route('/index')
def index():
    """
    主页的处理函数, 返回主页的响应
    """
    return render_template('blog_index.html')


@main.route('/new')
def new():
    """
    主页的处理函数, 返回主页的响应
    """
    return render_template('blog_new.html')


@main.route('/detail')
def detail():
    """
    主页的处理函数, 返回主页的响应
    """
    return render_template('blog_detail.html')

routes/routes_todo.py
from flask import (
    render_template,
    Blueprint,
)

# 创建一个蓝图对象
# 路由都定义在蓝图对象中
# 然后再 flask 主代码中 注册蓝图 来使用
# 第一个参数是蓝图的名字 以后会有用
# 第二个参数是套路
main = Blueprint('todo', __name__)


@main.route('/index')
def index():
    """
    主页的处理函数, 返回主页的响应
    """
    return render_template('todo.html')

templates/blog_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新建博客</title>
</head>
<body>
        <div class="gua-center-block gua-block">
            <h1 id="id-blog-title" class="gua-center"></h1>
            <div id="id-blog-content" class="markdown-body"></div>
        </div>
</body>
    <link href="https://cdn.bootcss.com/pure/1.0.0/pure-min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='markdown.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='gua.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='blog.css') }}" rel="stylesheet">
    <script src="https://cdn.bootcss.com/marked/0.3.6/marked.min.js"></script>
    <script src="{{ url_for('static', filename='gua.js') }}"></script>
    <script src="{{ url_for('static', filename='blog_detail.js') }}"></script>

</html>

templates/blog_index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>web15 blog</title>
    </head>
    <body>
        <h1 class="gua-center">web15 blog</h1>
        <div class="gua-center">
            <a href="{{ url_for('blog.new') }}" class="pure-button pure-button-primary">新建博客</a>
        </div>
        <table class="gua-center-block pure-table pure-table-striped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Updated Time</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody id="id-blog-list" >

            </tbody>
        </table>
        <!-- 这是我们处理静态文件的套路 -->
        <!-- gua.js 放了公共的函数 -->
        <!-- 按顺序引入 2 个 js 文件, 后面的 js 文件就能使用前面的文件中的函数了 -->
        <link href="https://cdn.bootcss.com/pure/1.0.0/pure-min.css" rel="stylesheet">
        <link href="{{ url_for('static', filename='gua.css') }}" rel="stylesheet">
        <script src="{{ url_for('static', filename='gua.js') }}"></script>
        <script src="{{ url_for('static', filename='blog_index.js') }}"></script>
    </body>
</html>

templates/blog_new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新建博客</title>
</head>
<body>
        <form class="gua-center-block gua-block pure-form" action="{{ url_for('blog_api.add') }}" method="POST">
            <input id="id-input-title" name="title" placeholder="标题">
            <textarea id="id-input-content" name="content" placeholder="正文"></textarea>
            <button id="id-button-add" class="pure-button pure-button-primary">发表博客</button>
        </form>
</body>
    <link href="https://cdn.bootcss.com/pure/1.0.0/pure-min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='gua.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='blog.css') }}" rel="stylesheet">
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>吃瓜主页</title>
</head>
<body>
    <h1>Hello {{username}}</h1>
    <img src="/static/doge.gif"/>
    <img src="/static/doge1.jpg"/>
    <img src="/static/doge2.gif"/>
    <br>
    <a href="{{ url_for('user.login') }}">Login</a>
    <a href="{{ url_for('user.register') }}">Register</a>
    <a href="{{ url_for('todo.index') }}">Todo</a>
    <a href="{{ url_for('blog.index') }}">Blog</a>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册登录页面</title>
</head>
<body>
    <h1>登录</h1>
    <h2>你好 {{username}}</h2>
    <form action="{{ url_for('user_api.login') }}" method="post">
        <input type="text" name="username" placeholder="请输入用户名">
        <br>
        <input type="text" name="password" placeholder="请输入密码">
        <br>
        <button type="submit">登录</button>
    </form>
    <h3>{{result}}</h3>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页面</title>
</head>
<body>
    <h1>注册</h1>
    <form action="/register" method="post">
        <input type="text" name="username" placeholder="请输入用户名">
        <br>
        <input type="text" name="password" placeholder="请输入密码">
        <br>
        <button type="submit">注册</button>
    </form>
</body>
</html>

templates/todo.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>web15 ajax flask todo with css</title>
    </head>
    <body>
        <h1 class="gua-center">web15 ajax flask todo with css</h1>
        <div class="gua-center pure-form">
            <input id='id-input-todo'>
            <button id='id-button-add' class="pure-button pure-button-primary">添加</button>
        </div>
        <table class="gua-center-block pure-table pure-table-striped">
            <thead>
                <tr>
                    <th>Content</th>
                    <th>Updated Time</th>
                    <th>Delete</th>
                    <th>Edit</th>
                </tr>
            </thead>
            <tbody id="id-todo-list" >

            </tbody>
        </table>
        <!-- 这是我们处理静态文件的套路 -->
        <!-- gua.js 放了公共的函数 -->
        <!-- 按顺序引入 2 个 js 文件, 后面的 js 文件就能使用前面的文件中的函数了 -->
        <link href="https://cdn.bootcss.com/pure/1.0.0/pure-min.css" rel="stylesheet">
        <link href="{{ url_for('static', filename='gua.css') }}" rel="stylesheet">
        <script src='{{ url_for('static', filename='gua.js') }}'></script>
        <script src='{{ url_for('static', filename='todo.js') }}'></script>
    </body>
</html>